# Main docker compose file

version: '3.1'

services:
    # web server nginx
    web:
        image: nginx
        volumes:
            - ./config/nginx:/etc/nginx:ro
            - ./log/nginx:/var/log/nginx:rw
            - ./data/nginx/www:/var/www:ro
        ports:
            - "80:80"
#        environment:
#            - NGINX_HOST=metrics.local
#            - NGINX_PORT=80
    sql:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            # configuration
            - ./config/mysql/conf.d:/etc/mysql/conf.d
            - ./data/mysql/:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass

    monitor:
        image: grafana/grafana-oss:8.2.0
        restart: always
        ports:
            - "3000:3000"
        volumes:
            # configuration
            - ./config/grafana:/etc/grafana
            - ./config/grafana/provisioning:/etc/grafana/provisioning
            # data storage
            #- ./data/grafana/lib:/var/lib/grafana:rw
            #- ./data/grafana/lib/plugins:/var/lib/grafana/plugins:rw
            # log storage
            - ./log/grafana:/var/log/grafana
    
    prometheus:
        image: prom/prometheus
        restart: always
        volumes:
            # configuration
            - ./config/prometheus:/etc/prometheus
        environment:
            - HOST:"172.18.0.1"
        ports:
            - "9090:9090"

    mysqlexport:
        image: prom/mysqld-exporter
        restart: always
        ports:
            - "9104:9104"
        links:
            - "sql:mysql"
        environment:
            DATA_SOURCE_NAME: "exporter:exporter@(sql:3306)/"
